mem:
  # If your HPC resource has a high memory capacity node you can set this to
  # the number of high-memory cores you want to use  (set to 0 otherwise)
  # and specify the amount of memory per core (e.g. if a node has 260 gb of
  # RAM and 10 cores it would be 26).
  big_mem_avail: 0
  big_mem_per_core_gb: 26
  # Memory per core of your computing resource.
  normal_mem_per_core_gb: 8
# Path to a temporary directory to write to.
tmp_dir: tmp
raws:
  # Path to test assembly fasta.
  assembly:  "test/contigs_4bins.fa"
  # Path to a test bam files to calculate depth from.
  metagenomics_alignment: "test/reads_4bins*.bam"
  # Path to an average depth per contig tsv file. Leave empty for initialization.
  contig_depth: ""
# Sample name
sample: "test"
# Path to desired output dir binny should create and store results in.
outputdir: "test_output"
# Absolute path to put binny dbs in. If left empty they will be put into 'database' in the binny main dir.
db_path: ""
# If you want to use existing environments containing the environments for Snakemake, Prokka
# and/or Mantis you can either input the absolute paths to yaml files or env names here.
# Otherwise, leave empty and binny will take care of the installations.
# If you already have Snakemake in your path set: snakemake_env="in_path".
snakemake_env: ""
prokka_env: ""
mantis_env: ""
# Set path for conda envs to be installed to. By default, they will be put in `conda` in the binny dir.
conda_source: ""
c