mem:
  normal_mem_per_core_gb: 4
  big_mem_per_core_gb: 40
tmp_dir: tmp
raws: 
  Contigs: "test/assembly.fasta"
  Alignment_metagenomics: "test/mg.reads.sorted.bam"
sample: test
outputdir: "binny_initialized"
db_path: "database"
binning:
  binny:
    pk: 10
    nn: 4
  vizbin:
    dimension: 50
    kmer: 5
    size: 4
    theta: 0.5
    perp: 30
    cutoff: 1000
