mem:
  big_mem_avail: FALSE
  normal_mem_per_core_gb: 4
  big_mem_per_core_gb: 40
tmp_dir: tmp
raws:
  Contigs: "test/assembly.fasta"
  Alignment_metagenomics: "test/mg.reads.sorted.bam"
  Contig_depth: ""
sample: test
outputdir: "binny_initialized"
db_path: "database"
binning:
  binny:
    pk: 10
    nn: 4
<<<<<<< Updated upstream
  vizbin:
    dimension: 50
    kmer: 5
    size: 4
    theta: 0.5
    perp: 30
    cutoff: 1000
  filtering:
    completeness: 25
=======
    kmers: '2,3,4'
    cutoff: 1000
  filtering:
    completeness: 90
>>>>>>> Stashed changes
    purity: 90
