mem:
  normal_mem_per_core_gb: 4
  big_mem_per_core_gb: 40
tmp_dir: tmp
raws: 
  Contigs: ""
  Alignment_metagenomics: ""
sample: test
outputdir: "test"
db_path: "/data/idiv_biu/heintzbu/EXTDB/IMP_DBs"
binning:
  binny:
    pk: 10
    nn: 4
  vizbin:
    dimension: 50
    kmer: 5
    size: 4
    theta: 0.5
    perp: 30
    cutoff: 1000
