__default__: 
  call: "sbatch --nodelist="
  nodes: "-N 1"
  partition: ""
  qos: ""
  mem_per_cpu: "--mem-per-cpu "  
  runtime: "-t "
  threads: "-c "
  stdout: "-o binny.{rule}.{wildcards}.stdout"

